package com.renterp.domain.file.storage;

import java.io.IOException;
import java.io.InputStream;

/**
 * Where uploaded bytes live. {@link LocalFileStorage} is the development
 * implementation; an S3 or Supabase Storage implementation only has to
 * implement these three calls - keys, metadata and the HTTP API stay the same.
 *
 * Keys are generated by {@code FileService}, never taken from a client.
 */
public interface FileStorage {

    void store(String key, InputStream content, long size, String contentType) throws IOException;

    InputStream open(String key) throws IOException;

    void delete(String key) throws IOException;
}
