# Regenerates docs/BRANCH_COMMITS.md: the commits on the current branch that
# are not on main, oldest first.
# Run from the repository root:  .\scripts\update_branch_log.ps1
# (If scripts are blocked: powershell -ExecutionPolicy Bypass -File scripts\update_branch_log.ps1)
$ErrorActionPreference = 'Stop'
$root = (git rev-parse --show-toplevel).Trim()
$branch = (git rev-parse --abbrev-ref HEAD).Trim()
$out = Join-Path $root 'docs\BRANCH_COMMITS.md'
$log = @(git -c i18n.logOutputEncoding=UTF-8 log main..HEAD --reverse --date=format:'%Y-%m-%d' --pretty=format:'%h%x09%ad%x09%an%x09%s')
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Commits on `' + $branch + '`')
$lines.Add('')
$lines.Add('Commits not on `main`, oldest first. Generated by `scripts/update_branch_log.ps1` - do not edit by hand.')
$lines.Add('Why each change was made: `docs/devlog/DEVLOG_APP_INTEGRATION.md`.')
$lines.Add('')
$lines.Add('| # | Hash | Date | Author | Subject |')
$lines.Add('|---|---|---|---|---|')
$n = 0
foreach ($entry in $log) {
    if (-not $entry) { continue }
    $p = $entry -split "`t", 4
    if ($p.Count -lt 4) { continue }
    $n++
    $subject = $p[3].Replace('|', '\|')
    $lines.Add('| ' + $n + ' | `' + $p[0] + '` | ' + $p[1] + ' | ' + $p[2] + ' | ' + $subject + ' |')
}
$text = ($lines -join "`n") + "`n"
[IO.File]::WriteAllText($out, $text, (New-Object Text.UTF8Encoding $false))
Write-Host ('Wrote ' + $out + ' (' + $n + ' commits on ' + $branch + ')')
